INSERT INTO public.model (manufacturer, name) VALUES ('China', 'Xiaomi Mi Electric Scooter Pro 2');
INSERT INTO public.model (manufacturer, name) VALUES ('China', 'Xiaomi Mijia Electric Scooter Pro');
INSERT INTO public.model (manufacturer, name) VALUES ('China', 'Xiaomi MIJIA Electric Scooter 1S');
INSERT INTO public.model (manufacturer, name) VALUES ('China', 'Xiaomi Mijia M365');
INSERT INTO public.model (manufacturer, name) VALUES ('Germany', 'Citybird T2');
INSERT INTO public.model (manufacturer, name) VALUES ('Germany', 'Citybird Swift');
INSERT INTO public.model (manufacturer, name) VALUES ('USA', 'Ninebot KickScooter MAX');
INSERT INTO public.model (manufacturer, name) VALUES ('USA', 'Ninebot Max Plus');
INSERT INTO public.model (manufacturer, name) VALUES ('USA', 'Ninebot Max Pro');
INSERT INTO public.model (manufacturer, name) VALUES ('USA', 'Ninebot Max');
INSERT INTO public.model (manufacturer, name) VALUES ('Russia', 'Kugoo G1 Jilong');
INSERT INTO public.model (manufacturer, name) VALUES ('Russia', 'Kugoo Max Speed 11 Ah Jilong');
INSERT INTO public.model (manufacturer, name) VALUES ('Russia', 'Kugoo HX Pro Jilong');
INSERT INTO public.model (manufacturer, name) VALUES ('Russia', 'Kugoo M4 Pro 13.5Ah Jilong');
