jwt:
  secretKey: "kicksharingmegaverysupersecretkey"
  tokenPrefix: ""
  tokenExpirationAfterDays: 14
manager-token: "manager_token"

spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          ssl:
            enable: 'true'
          auth: 'true'
    host: smtp.yandex.ru
    username: spring-server@yandex.ru
    password: y/%-q%,Rz[#SV9J
    port: '465'

  kafka:
    bootstrap-servers: 'localhost:9092'